### ISSUE TITLE
Errors in Python imports to read in .gctx file

### ISSUE THREAD

**Issue by jamesdj** [cmap/l1ktools#25]
I'm trying to read in a .gctx file in Python and write it as a .gct file. If I follow the instructions in the GitHub readme, I get the following error:

```
ImportError                               Traceback (most recent call last)
<ipython-input-3-e0a25a8c6650> in <module>()
----> 1 from cmap.io.gct import GCT

ImportError: No module named 'cmap'
```

This despite having appended l1ktools/python to the PYTHONPATH environment variable.

Poking around, I found what seemed like it should be the correct way:

`from broadinstitute_cmap.io.GCToo import gctx2gct`

But this gives me

```
ImportError                               Traceback (most recent call last)
<ipython-input-2-7831cb2cb011> in <module>()
----> 1 from broadinstitute_cmap.io.GCToo import gctx2gct

/home/jamesdj/anaconda3/pkgs/l1ktools/python/broadinstitute_cmap/io/GCToo/gctx2gct.py in <module>()
     10 
     11 import logging
---> 12 import setup_GCToo_logger as setup_logger
     13 import argparse
     14 import sys

/home/jamesdj/anaconda3/pkgs/l1ktools/python/broadinstitute_cmap/io/GCToo/setup_GCToo_logger.py in <module>()
      1 import logging
      2 import logging.handlers
----> 3 import ConfigParser
      4 import os.path
      5 

ImportError: No module named 'ConfigParser'
```

**Comment by levlitichev** [comment]
Hi James, Thanks for opening this issue. You're right -- that import statement should be `broadinstitute_cmap.io.GCToo` as you pointed out.

The second problem is related to the fact that it looks like you're using python3. The GCToo library was written for python2, but we're working on ensuring forward compatibility with python3. In the meantime, if you change your import statement from `import ConfigParser` to `import configparser`, things should work.

Let us know if that doesn't work.

**Comment by dllahr** [comment]
Is this issue resolved now?

**Comment by jamesdj** [comment]
Yes, I think so.

On Feb 6, 2017 5:21 AM, "Dave Lahr" <notifications@github.com> wrote:

Is this issue resolved now?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/cmap/l1ktools/issues/25#issuecomment-277678608>, or mute
the thread
