### ISSUE TITLE
S3ify adds the users api key to the payload 

### ISSUE THREAD

**Issue by jasiedu** [cmap/l1ktools#28]
It looks like when S3ify updates or creates a new record via the clue api for the macchiato end point, it adds a user_key field to the payload.

{ 
    "_id" : ObjectId("581bb3e0cdca264111f5f86f"), 
    "brew_prefix" : "LIVF003_HUH751_XH", 
    "status" : "UPLOADED", 
    "created" : ISODate("2016-11-03T22:02:08.763+0000"), 
    "last_modified" : ISODate("2016-11-03T22:15:47.151+0000"), 
    "user_key" : "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
}

**Comment by dllahr** [comment]
fixed with commit 04a7a1119ac00bf8f5eec3876160220ec1447546
