### ISSUE TITLE
python/broadinstitute_cmap/io/pandasGEXpress/parse_gctx  needs to handle rid parameter that is list of integers

### ISSUE THREAD

**Issue by dllahr** [cmap/l1ktools#33]
python/broadinstitute_cmap/io/pandasGEXpress/parse_gctx

In the parse method, if the parameter rid is supplied with a list of integers, the code fails, incorrectly assigning them to be ridx.  The code needs to treat rid as rid and ridx as ridx, not try to infer them by type.  Same goes for cid / cidx.

**Comment by oena** [comment]
Should be fixed!
