### ISSUE TITLE
fold change

### ISSUE THREAD

**Issue by marouenbg** [cmap/l1ktools#35]
Would it be possible to have level 4 data with fold change instead of zscore?
Thank you

**Comment by tnat1031** [comment]
Hi @marouenbg,

Our pipeline doesn't currently support fold change as a differential
expression metric, but you are welcome to add that and send a pull request
if you'd like.
We generally prefer the z-score approach as it accounts for both magnitude
and variance of expression across a population of samples (typically the
other 383 wells in an assay plate).
Is there a reason you prefer fold change?

Thanks a lot,
Ted

**Comment by marouenbg** [comment]
Thanks @tnat1031 ! I will definitly make a PR to add FC as a metric.
The reason is that we have an internal processing pipeline that uses FC.

Thanks for your help.

**Comment by tnat1031** [comment]
sounds good!
