### ISSUE TITLE
hdf5 and h5r have been removed from the CRAN repository, edit README

### ISSUE THREAD

**Issue by shntnu** [cmap/l1ktools#5]
hdf5 and h5r have been removed from the CRAN repository. Consider adding instructions to the README

brew install hdf5 (for OS X)
wget http://cran.r-project.org/src/contrib/Archive/hdf5/hdf5_1.6.9.tar.gz
wget http://cran.r-project.org/src/contrib/Archive/h5r/h5r_1.4.7.tar.gz
install.packages("hdf5_1.6.9.tar.gz", repos=NULL, type="source”)
install.packages("h5r_1.4.7.tar.gz", repos=NULL, type="source”)

**Comment by tnat1031** [comment]
We have recently updated to use the rhdf5 package which should resolve this issue. Please let us know if you still experience problems.
