### ISSUE TITLE
R code gives "negative length vectors are not allowed" error

### ISSUE THREAD

**Issue by polojacky** [cmap/l1ktools#7]
First I gave a list of cids to the function parse.gctx(gctxFile,cid=distil_id), and it returned "negative length vectors are not allowed " error. Then I tried two cids such as c("ASG001_MCF7_24H_X1_B7_DUO52HI53LO:A06","ERG005_VCAP_48H_X1_B1_UNI5253L:M03"), it produced the same error? Is it because the two ids are too far away from each other in the big gctx file (level4 gctx file)?

Added: The indexes of these two ids are 17 and 345399. What's more, if I load the entire LINCS level4 gctx file into memory (512G linux server), it gives the same error, but python code is ok. So the R code is not well enough compared with python code?

**Comment by tnat1031** [comment]
We have recently updated to use the rhdf5 package and this issue should now be resolved. Please let us know if you still experience problems.
